name: fave_films_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.4
  get: ^4.6.6
  get_it: ^7.6.7
  http: ^1.1.0
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
      - asset: assets/fonts/PoppinsRegular.ttf
      - asset: assets/fonts/PoppinsBold.ttf
      - asset: assets/fonts/PoppinsBoldItalic.ttf
      - asset: assets/fonts/PoppinsItalic.ttf
      - asset: assets/fonts/PoppinsMedium.ttf
      - asset: assets/fonts/PoppinsSemiBold.ttf